import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ChevronRight, Keyboard, RotateCcw, Sparkles, Target, Trophy, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';

type Lesson = { id:number; level:string; title:string; subtitle:string; exercises:string[]; tips:string[]; focus:string; };

const lessons: Lesson[] = [
{id:1,level:'Beginner',title:'Home Row Fundamentals',subtitle:'Build strong finger placement with ASDF and JKL; before moving ahead.',focus:'ASDF + JKL;',tips:['Keep the left hand on A S D F and right hand on J K L ;.','Both thumbs should rest naturally near the spacebar.','Accuracy and relaxed fingers are more important than speed.','Complete all 3 practice rounds before marking the lesson complete.'],exercises:[
'asdf jkl; asdf jkl; fdsa ;lkj asdf jkl; aaaa ssss dddd ffff jjjj kkkk llll ;;;; asdf asdf jkl; jkl; fdsa lk j; asdf jkl; fds a jkl; a s d f j k l ; asdf jkl; asdf jkl; fdsa ;lkj. Repeat the home row groups slowly and keep every finger close to its starting position. Do not look down at the keyboard. Return each finger to the home row after every movement.',
'asdf jkl; jkl; asdf fdsa ;lkj fads jkl; asdf jkl; aaaa ssss dddd ffff jjjj kkkk llll ;;;; aa ss dd ff jj kk ll ;; asdf fdsa jkl; ;lkj asdf jkl; fdsa lk j; sad fads jkl; ask lad fall; dad sad; all fall; flask; ask; add; lad; salad; Practice these groups at a calm pace. If one finger becomes confused, stop, place both hands correctly, and start the group again.',
'a s d f   j k l ;   asdf jkl;   fdsa ;lkj   asdf asdf jkl; jkl;   fads lad ask fall salad;   all dads ask;   sad lad;   flask falls;   a lad asks;   all fall;   Repeat this complete drill several times. Your goal is not a high WPM. Your goal is to make the home-row movement feel natural so that your fingers can find the keys without looking.'
]},
{id:2,level:'Beginner',title:'Top Row & Home Row Reach',subtitle:'Learn QWERTY top-row movement while returning to the home position.',focus:'Q W E R T + Y U I O P',tips:['Reach from the home row; do not lift the whole hand.','Return to the home row after each reach.','Keep your eyes on the text instead of your fingers.','Repeat difficult key combinations until they feel automatic.'],exercises:[
'qwer tyui op qwer tyui qwer asdf tyui jkl; we er rt yu ui io op qw we er rt ty yu ui io op. Move slowly from the home row to the top row and back. Keep your wrist steady and let the fingers do the work. qwer qwer tyui tyui asdf asdf jkl; jkl; qwer asdf tyui jkl; qwer asdf tyui jkl; Practice the same patterns again without looking down.',
'we were write water word work world tree three true quiet quite quick queen question type typing top stop step open people power paper. qwer tyui op; qwer asdf tyui jkl; The quick brown fox jumps over the lazy dog. Practice common words slowly, then repeat them with a smoother rhythm. If you miss a key, reduce speed and focus on the correct finger.',
'qwerty qwerty uiop uiop qwer tyui asdf jkl; quiet quick quality water write worker computer keyboard student project practice. Every word is a combination of familiar finger movements. Read a few words ahead, keep your shoulders relaxed, and return your fingers to the home row after each reach. Repeat this round until the top-row keys feel comfortable.'
]},
{id:3,level:'Beginner',title:'Bottom Row & Full Alphabet',subtitle:'Add Z X C V B N M and combine all three letter rows.',focus:'Z X C V B N M',tips:['Use the correct finger for each bottom-row key.','Keep your palms still and move only the needed fingers.','Slow down on unfamiliar combinations.','Mix all three rows so your hands learn real movement.'],exercises:[
'zxcv bnm, zxcv bnm, zxcv asdf bnm, jkl; cvcv vbbn nmnm mmmm zzzz xxxx cccc vvvv bbbb nnnn mmmm. Reach down from the home row and immediately return. Do not look at your hands. Practice the bottom row in small groups and keep the movement relaxed.',
'zoo box mix wax quiz jump zebra cabin brown black calm move brave amazing maximum minimum example problem quick fox van can man name home some time come. Combine top, middle, and bottom rows into real words. Type each word carefully and use one clean space between words. Repeat the word groups until you can type them without hesitation.',
'quick brown fox jumps over the lazy dog; every letter can be found with correct finger movement. The keyboard has three main letter rows, and strong typists move between them without thinking about every individual key. Practice alphabet patterns, short words, and full sentences. Stay accurate and let speed develop naturally.'
]},
{id:4,level:'Easy',title:'Words, Spaces & Rhythm',subtitle:'Turn individual keys into smooth words and consistent typing rhythm.',focus:'Words + spacing',tips:['Use one space between words.','Read one or two words ahead when possible.','Do not rush the first few words of a sentence.','Keep the same comfortable rhythm for longer passages.'],exercises:[
'the and you are for with this that have from they will your what there about which their would these other words typing learn practice skill speed accuracy good work fast hands calm mind daily practice makes typing easier. Type each word as a complete unit and keep your spaces consistent. Try not to pause after every word.',
'computer keyboard student college future project website coding practice progress accuracy speed lesson learning morning evening simple useful important regular comfortable confident. Good typing comes from regular practice. A calm typist keeps the eyes on the text and lets the fingers move naturally. Repeat this paragraph while keeping your rhythm steady.',
'Learning to type well takes patience and practice. Small improvements repeated every day can become strong habits. Keep your hands relaxed, look at the screen, and avoid checking the keyboard. If you make a mistake, stay calm and continue. Your goal is smooth, accurate typing from the beginning of the sentence to the end.'
]},
{id:5,level:'Easy',title:'Capital Letters & Punctuation',subtitle:'Use Shift and common punctuation confidently in real sentences.',focus:'Shift + punctuation',tips:['Use the opposite hand for Shift when possible.','Release Shift after the capital letter.','Watch commas, full stops, apostrophes and question marks.','Keep spacing consistent around punctuation.'],exercises:[
'Typing is a skill, and every skill improves with practice. Can you type this sentence correctly? Yes, you can! Keep learning, keep practicing, and stay accurate. A calm typist makes fewer mistakes. Today, we will practice English sentences, capital letters, and punctuation. Remember: accuracy comes first.',
'My goal is to improve slowly. What should I do when I make a mistake? Stay calm and continue. "Practice" builds confidence; accuracy builds speed. Do not rush, and do not look down at the keyboard. Use Shift with the opposite hand when possible, then return to the home row.',
'Typing is useful for college work, coding, applications, reports, emails, and everyday communication. In 2026, digital skills are important for students and professionals. Practice commas, full stops, question marks, apostrophes, colons, and semicolons carefully. Read the sentence first, then type it with a steady rhythm.'
]},
{id:6,level:'Intermediate',title:'Numbers & Special Characters',subtitle:'Build confidence with numbers, symbols, email, code and data-entry patterns.',focus:'Numbers + symbols',tips:['Learn the number row gradually instead of rushing.','Keep your eyes on the screen.','Treat every digit as important in data-entry practice.','Practice common symbols until they stop interrupting your rhythm.'],exercises:[
'2026 12345 67890 10 20 30 40 50 100 250 500 1000 2026 123 456 789. Practice number groups slowly and keep the fingers controlled. Repeat the groups several times. 12 34 56 78 90; 111 222 333 444 555; 101 202 303 404 505.',
'email@example.com user123@example.com total = 250 + 50 score: 98% speed: 40 WPM code_101 price $499 discount 20% room 7 floor 3 date 18/09/2026 marks 42/50 8GB RAM i5-6500 HTML/CSS/JS Python 3.12. Type every symbol carefully and keep the spacing readable.',
'Numbers and symbols are important in modern typing. Students use them in assignments, programmers use them in code, and office workers use them in reports and spreadsheets. One wrong digit can change a result. Practice 10 + 20 = 30, 50 - 15 = 35, 5 * 5 = 25, and 100 / 4 = 25. Stay relaxed and accurate.'
]},
{id:7,level:'Intermediate',title:'Sentence & Paragraph Flow',subtitle:'Move from drills to continuous paragraphs without losing rhythm.',focus:'Continuous typing',tips:['Read several words ahead before typing them.','Keep punctuation from breaking your rhythm.','Relax shoulders and wrists during long passages.','If you make an error, recover calmly and continue.'],exercises:[
'Typing practice becomes easier when your hands learn a natural rhythm. A good typist keeps the eyes on the text and the fingers on the keyboard. Regular practice improves accuracy, confidence, and speed. Do not rush every sentence; instead, build a smooth and reliable typing flow. With patience, difficult words become familiar and common patterns become automatic.',
'Before you begin, sit comfortably and place your fingers correctly. Read several words ahead, then type without unnecessary pauses. If you make a mistake, stay calm and continue. Keep your shoulders relaxed and avoid pressing the keys too hard. Long passages are useful because they teach you to maintain the same pace for several minutes.',
'Typing can become a valuable everyday skill. It helps with college work, coding projects, applications, office tasks, online forms, and communication. The more you practice correctly, the more automatic your finger movements become. Focus on control first, consistency second, and speed later. Repeat this lesson until the paragraph flow feels natural.'
]},
{id:8,level:'Hard',title:'Speed Building & Accuracy',subtitle:'Increase pace through controlled repetition instead of sacrificing accuracy.',focus:'Speed + accuracy',tips:['Start at a comfortable speed and increase gradually.','If errors increase sharply, slow down and rebuild control.','Relax your shoulders and wrists during speed work.','Use repeated rounds to make common patterns automatic.'],exercises:[
'Fast typing is built through accurate repetition. Start slowly, find a comfortable rhythm, and then increase your pace. Keep your fingers close to the keyboard and avoid unnecessary movement. When you feel tension, slow down, relax your shoulders, and continue. Consistent daily practice is more valuable than one very fast session.',
'Round one: type slowly and aim for clean accuracy. Round two: increase your pace slightly while keeping mistakes low. Round three: type the same passage at a comfortable challenge speed. Round four: return to a controlled pace and focus on smoothness. Speed should feel natural, not forced.',
'A focused student can improve typing through regular practice. Every session should have a clear purpose. Sometimes you train accuracy, sometimes rhythm, and sometimes speed. Small improvements repeated every day can produce strong results over time. Stay patient, stay relaxed, and keep your fingers moving with confidence.'
]},
{id:9,level:'Hard',title:'Exam-Style Practice',subtitle:'Prepare for longer typing tests with stable pace and clean accuracy.',focus:'Exam technique',tips:['Do not race during the first minute of a test.','Maintain a pace you can hold until the end.','Watch spacing and punctuation carefully.','If an error happens, stay calm and continue.'],exercises:[
'Typing tests require concentration, consistency, and patience. Before starting, sit comfortably and place your fingers correctly. Read the passage carefully and begin at a pace you can maintain. Keep your eyes on the text, use the correct fingers, and avoid looking down at the keyboard. Your goal is accurate, steady performance from beginning to end.',
'In a real test, the first minute should not be a race. Find your rhythm and settle into a comfortable pace. During the middle of the test, maintain that pace and watch your spacing. Near the end, do not panic or suddenly type much faster. Finish carefully and protect your accuracy.',
'Computer skills are increasingly important for students and professionals. Good typing helps people write assignments, create reports, enter data, communicate online, and work with software efficiently. A trained typist does not need to search for every key. Instead, the fingers move naturally while the eyes stay focused on the words. Treat this round like a mini exam.'
]},
{id:10,level:'Advanced',title:'Typing Academy Final Challenge',subtitle:'Combine everything: letters, capitals, punctuation, numbers and long-form typing.',focus:'Mastery',tips:['Accuracy remains the foundation of advanced typing.','Read ahead and keep a stable rhythm.','Do not look down at the keyboard.','Compare your accuracy and comfortable speed with earlier lessons.','After finishing, keep practicing regularly to maintain the skill.'],exercises:[
'Technology changes quickly, but strong typing remains a valuable skill. A confident typist can focus more on ideas and less on finding keys. Continue practicing every day, challenge yourself with longer passages, and gradually increase your target speed. Accuracy should remain your foundation. When your hands know the keyboard, writing becomes smoother, faster, and more comfortable.',
'In 2026, students can use typing skills for college projects, coding, online applications, reports, emails, spreadsheets, and many other tasks. A reliable typing speed of 30 WPM, 40 WPM, or 50 WPM is useful only when accuracy is strong. Try to maintain clean spacing, correct capitalization, and punctuation throughout the entire passage. If a mistake happens, recover calmly and continue.',
'Final challenge: Build your own rhythm. Read ahead. Keep your fingers relaxed. Do not look down. If you make a mistake, recover calmly. Continue typing until the passage is complete. Review your result and compare it with your earlier lessons. Your progress is the result of consistent practice, not one perfect attempt. Keep learning, keep improving, and use your typing skills in study, work, coding, and everyday life. Congratulations on reaching the final lesson!'
]}
];

const STORAGE_KEY='typemasterplus_learn_progress_v2';
export function Learn(){
 const [completed,setCompleted]=useState<number[]>(()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}});
 const [selected,setSelected]=useState(0); const [stage,setStage]=useState(0); const [input,setInput]=useState('');
 const [lastKey,setLastKey]=useState(''); const inputRef=useRef<HTMLInputElement>(null); const lesson=lessons[selected];
 const exercise=lesson.exercises[stage]; const exerciseDone=input===exercise; const isComplete=completed.includes(lesson.id);
 const progress=Math.round(completed.length/lessons.length*100);
 useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(completed))},[completed]);
 useEffect(()=>{setInput('');setStage(0);setLastKey('');setTimeout(()=>inputRef.current?.focus(),60)},[selected]);
 const currentKey=input.length<exercise.length?exercise[input.length]:'';
 const keys=useMemo(()=>[['`','1','2','3','4','5','6','7','8','9','0','-','=','Backspace'],['Tab','Q','W','E','R','T','Y','U','I','O','P','[',']','\\'],['Caps','A','S','D','F','G','H','J','K','L',';','\'','Enter'],['Shift','Z','X','C','V','B','N','M',',','.','/','Shift'],['Ctrl','Alt','Space','Alt','Ctrl']],[]);
 const completeLesson=()=>{if(stage===2&&exerciseDone&&!completed.includes(lesson.id))setCompleted([...completed,lesson.id])};
 const nextStage=()=>{if(!exerciseDone)return;if(stage<2){setStage(stage+1);setInput('');setLastKey('');setTimeout(()=>inputRef.current?.focus(),60)}else completeLesson()};
 const selectLesson=(i:number)=>{setSelected(i);window.scrollTo({top:0,behavior:'smooth'})};
 return <div className="flex-1 w-full max-w-7xl mx-auto px-4 sm:px-6 py-6 md:py-10">
  <div className="text-center mb-8"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-yellow-500/10 border border-yellow-500/20 text-yellow-400 text-sm font-semibold mb-4"><Sparkles className="w-4 h-4"/> Typing Academy</div><h1 className="text-3xl md:text-5xl font-black text-white">Learn Typing from Basic to Advanced</h1><p className="text-slate-400 mt-3 max-w-2xl mx-auto">10 detailed lessons · 3 practice rounds per lesson · live keyboard · tips · progress tracking.</p></div>
  <div className="bg-slate-800/60 border border-slate-700 rounded-2xl p-4 md:p-5 mb-6"><div className="flex items-center justify-between gap-4 mb-3"><div className="flex items-center gap-3"><div className="p-2 rounded-xl bg-yellow-500/10"><Target className="w-5 h-5 text-yellow-400"/></div><div><p className="text-white font-bold">Your Progress</p><p className="text-xs text-slate-400">{completed.length} of {lessons.length} lessons completed</p></div></div><span className="text-yellow-400 font-black">{progress}%</span></div><div className="h-3 bg-slate-900 rounded-full overflow-hidden"><div className="h-full bg-yellow-500 rounded-full transition-all duration-500" style={{width:`${progress}%`}}/></div></div>
  <div className="grid lg:grid-cols-[290px_1fr] gap-6"><aside className="bg-slate-800/50 border border-slate-700 rounded-2xl p-3 h-fit"><div className="px-3 py-3 flex items-center gap-2 text-white font-bold"><BookOpen className="w-5 h-5 text-yellow-400"/> Lessons</div><div className="space-y-1">{lessons.map((item,i)=><button key={item.id} onClick={()=>selectLesson(i)} className={`w-full text-left p-3 rounded-xl flex items-center gap-3 transition ${i===selected?'bg-yellow-500 text-slate-950':'hover:bg-slate-700/70 text-slate-300'}`}><span className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${i===selected?'bg-slate-950/10':'bg-slate-700'}`}>{completed.includes(item.id)?<CheckCircle2 className="w-5 h-5"/>:item.id}</span><span className="min-w-0 flex-1"><span className="block font-semibold truncate">{item.title}</span><span className={`block text-xs ${i===selected?'text-slate-800/70':'text-slate-500'}`}>{item.level}</span></span></button>)}</div></aside>
  <main className="min-w-0"><div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-5 md:p-8"><div className="flex flex-wrap items-start justify-between gap-4 mb-6"><div><div className="flex items-center gap-2 text-yellow-400 text-sm font-bold mb-2"><Zap className="w-4 h-4"/> Lesson {lesson.id} · {lesson.level}</div><h2 className="text-2xl md:text-3xl font-black text-white">{lesson.title}</h2><p className="text-slate-400 mt-2">{lesson.subtitle}</p></div>{isComplete&&<div className="inline-flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 px-3 py-2 rounded-full text-sm font-bold"><CheckCircle2 className="w-4 h-4"/> Completed</div>}</div>
  <div className="flex items-center justify-between mb-3"><span className="text-sm font-bold text-white">Practice Round {stage+1} of 3</span><span className="text-xs text-yellow-400">Long-form lesson</span></div>
  <div className="bg-slate-950/60 border border-slate-700 rounded-2xl p-5 mb-6"><div className="flex items-center gap-2 text-slate-300 text-sm font-semibold mb-4"><Keyboard className="w-4 h-4 text-yellow-400"/> Type this exactly</div><div className="text-slate-100 font-mono text-base md:text-lg leading-8 py-3 break-words">{exercise.split('').map((c,i)=><span key={i} className={i<input.length?(input[i]===c?'text-emerald-400':'text-red-400 bg-red-500/10'):i===input.length?'text-yellow-300 underline decoration-yellow-400':'text-slate-300'}>{c}</span>)}</div><input ref={inputRef} value={input} onChange={e=>{const v=e.target.value.slice(0,exercise.length);setInput(v);if(v) setLastKey(v[v.length-1])}} onKeyDown={e=>setLastKey(e.key)} autoComplete="off" autoCorrect="off" spellCheck={false} className="w-full mt-4 bg-slate-900 border border-slate-700 focus:border-yellow-500 outline-none rounded-xl px-4 py-3 text-white font-mono text-base" placeholder="Start typing here..."/><div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-500"><span>Next key: <b className="text-yellow-400">{currentKey===' '?'SPACE':currentKey||'—'}</b></span><span>•</span><span>{input.length}/{exercise.length} characters</span>{lastKey&&<><span>•</span><span>Last key: <b className="text-emerald-400">{lastKey===' '?'SPACE':lastKey}</b></span></>}</div></div>
  <div className="bg-slate-950/40 border border-slate-700 rounded-2xl p-4 md:p-6 mb-6"><div className="flex items-center justify-between mb-4"><h3 className="text-white font-bold flex items-center gap-2"><Keyboard className="w-5 h-5 text-yellow-400"/> Live Keyboard</h3><span className="text-xs text-slate-500">Next required key is highlighted</span></div><div className="space-y-2 max-w-4xl mx-auto">{keys.map((row,ri)=><div key={ri} className={`flex justify-center gap-1.5 ${ri===4?'px-10':''}`}>{row.map((key,ki)=>{const active=!!currentKey&&((key.length===1&&key.toLowerCase()===currentKey.toLowerCase())||(key==='Space'&&currentKey===' '));const wide=['Backspace','Tab','Caps','Enter','Shift','Ctrl','Alt'].includes(key);return <div key={ki} className={`${wide?'px-2 md:px-4 min-w-[48px]':key==='Space'?'px-12 md:px-28':'w-8 md:w-11'} h-9 md:h-11 rounded-lg border flex items-center justify-center text-[10px] md:text-xs font-bold transition-all ${active?'bg-yellow-500 text-slate-950 border-yellow-400 scale-105 shadow-lg shadow-yellow-500/20':'bg-slate-800 border-slate-700 text-slate-400'}`}>{key}</div>})}</div>)}</div></div>
  <div className="grid md:grid-cols-2 gap-4 mb-6"><div className="bg-slate-900/50 rounded-2xl p-5 border border-slate-700"><h3 className="text-white font-bold mb-3">Lesson Tips</h3><ul className="space-y-2">{lesson.tips.map(t=><li key={t} className="text-sm text-slate-400 flex gap-2"><CheckCircle2 className="w-4 h-4 text-yellow-400 shrink-0 mt-0.5"/>{t}</li>)}</ul></div><div className="bg-yellow-500/5 rounded-2xl p-5 border border-yellow-500/20"><h3 className="text-white font-bold mb-3">Focus</h3><p className="text-2xl font-black text-yellow-400">{lesson.focus}</p><p className="text-sm text-slate-400 mt-2">Complete all 3 rounds. A full lesson is intentionally longer so the user gets real practice time.</p></div></div>
  {exerciseDone&&!isComplete&&<div className="mb-5 rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-5 text-center"><Trophy className="w-8 h-8 text-emerald-400 mx-auto mb-2"/><h3 className="text-xl font-black text-white">Round {stage+1} complete 🎉</h3><p className="text-slate-400 text-sm mt-1">{stage<2?'Continue to the next practice round.':'All 3 rounds are complete. Finish the lesson to save your progress.'}</p></div>}
  {isComplete&&<div className="mb-5 rounded-2xl border border-yellow-500/30 bg-yellow-500/10 p-5 text-center"><Trophy className="w-8 h-8 text-yellow-400 mx-auto mb-2"/><h3 className="text-xl font-black text-white">Congratulations! 🎉</h3><p className="text-slate-400 text-sm mt-1">You completed Lesson {lesson.id}. Keep going!</p></div>}
  <div className="flex flex-wrap justify-between gap-3"><button disabled={selected===0} onClick={()=>selectLesson(selected-1)} className="px-4 py-3 rounded-xl bg-slate-700 text-white font-bold disabled:opacity-30 flex items-center gap-2"><ArrowLeft className="w-4 h-4"/> Previous</button><div className="flex gap-2"><button onClick={()=>{setInput('');setLastKey('')}} className="px-4 py-3 rounded-xl bg-slate-700 hover:bg-slate-600 text-white font-bold flex items-center gap-2"><RotateCcw className="w-4 h-4"/> Reset Round</button>{!isComplete&&<button disabled={!exerciseDone} onClick={nextStage} className="px-5 py-3 rounded-xl bg-yellow-500 hover:bg-yellow-400 text-slate-950 font-black disabled:opacity-40 flex items-center gap-2"><CheckCircle2 className="w-4 h-4"/>{stage<2?'Next Round':'Complete Lesson'}</button>}<button disabled={selected===lessons.length-1} onClick={()=>selectLesson(selected+1)} className="px-4 py-3 rounded-xl bg-slate-700 hover:bg-slate-600 text-white font-bold disabled:opacity-30 flex items-center gap-2">Next <ArrowRight className="w-4 h-4"/></button></div></div>
  </div></main></div>
  {completed.length===lessons.length&&<div className="mt-6 bg-gradient-to-r from-yellow-500/15 to-emerald-500/10 border border-yellow-500/30 rounded-2xl p-8 text-center"><Trophy className="w-12 h-12 text-yellow-400 mx-auto mb-3"/><h2 className="text-3xl font-black text-white">Typing Academy Completed! 🎉</h2><p className="text-slate-400 mt-2 mb-5">Congratulations! You finished all 10 detailed lessons.</p><Link to="/practice" className="inline-flex items-center gap-2 bg-yellow-500 hover:bg-yellow-400 text-slate-950 font-black px-6 py-3 rounded-xl">Start Typing Practice <ChevronRight className="w-4 h-4"/></Link></div>}
 </div>
}
